<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_length"  value="2.5"/>
    <xacro:property name="base_width"  value="1.5"/>
    <xacro:property name="base_height"  value="1"/>
    
    <xacro:property name="wheel_radius"  value="0.4"/>
    <xacro:property name="wheel_length"  value="0.20"/>
    
    <xacro:property name="gps_length" value="0.1"/>
    <xacro:property name="gps_width" value="0.1"/>
    <xacro:property name="gps_height" value="0.05"/>

    <xacro:property name="dif_length" value="0.05"/>
    <xacro:property name="dif_radius" value="0.02"/>


    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5" l="${base_height}" w="${base_length}" h="${base_width}"
                                xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <!-- SAĞ-SOL TEKER DİFERANSİYEL -->
    <xacro:macro name="dif_link" params="prefix">
        <link name="${prefix}_front_dif"> 
            <visual>
                <geometry>
                    <cylinder length="${dif_length}" radius="${dif_radius}"/>
                </geometry>
                <origin xyz= "0 0 0" rpy="0 0 0"/>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${dif_length}" radius="${dif_radius}"/>
                </geometry>
                <origin xyz= "0 0 0" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1" r="${2*dif_radius}" l="${2*dif_length}"
                            xyz="0 0 0" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:dif_link prefix="right"/>
    <xacro:dif_link prefix="left"/>

    <xacro:macro name="wheel_link" params="prefix radius_ length_ z_offset">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius_}" length="${length_}" />
                </geometry>
                <origin xyz="0 0 ${z_offset/2.0}" rpy="0 0 0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius_}" length="${length_}" />
                </geometry>
                <origin xyz="0 0 ${z_offset/2.0}" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2+radius_}" l="${2+length_}"
                    xyz="0 0 ${z_offset/2.0}" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right_front" radius_="${wheel_radius}" length_="${wheel_length}"  z_offset="0"/>
    <xacro:wheel_link prefix="left_front" radius_="${wheel_radius}" length_="${wheel_length}" z_offset="0"/>

    <xacro:wheel_link prefix="right_back" radius_="${wheel_radius}" length_="${wheel_length}"  z_offset="${wheel_length}"/>
    <xacro:wheel_link prefix="left_back" radius_="${wheel_radius}" length_="${wheel_length}" z_offset="${-wheel_length}"/>
    

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="left_front_dif_joint" type="revolute">
        <parent link="base_link" />
        <child link="left_front_dif" />
        <origin xyz="${base_length / 4.0} ${(base_width/2.0) + (wheel_length/2.0)} 0" rpy="${pi/2.0} 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="1" lower="-1" upper="1"/>
        <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <joint name="right_front_dif_joint" type="revolute">
        <parent link="base_link" />
        <child link="right_front_dif" />
        <origin xyz="${base_length / 4.0} ${-((base_width/2.0) + (wheel_length/2.0))} 0" rpy="${pi/2.0} 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="1" lower="-1" upper="1"/>
        <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <joint name="left_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_back_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${base_width/2.0} 0" rpy="${pi/2.0} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <joint name="right_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_back_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-base_width/2.0} 0" rpy="${pi/2.0} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <joint name="left_front_dif_wheel_joint" type="continuous">
        <parent link="left_front_dif" />
        <child link="left_front_wheel_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 -1" />
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort="100" velocity="100"/>
    </joint>

    <joint name="right_front_dif_wheel_joint" type="continuous">
        <parent link="right_front_dif" />
        <child link="right_front_wheel_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 -1" />
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort="100" velocity="100"/>
    </joint>

</robot>